#!/usr/bin/env bash

# original script was taken from this github https://github.com/Shringe/dunst-media-control

volume_step=2
max_volume=100
notification_timeout=1000 # in milliseconds
enable_mpd_support=true
download_album_art=true
show_album_art=true
show_music_in_volume_indicator=true

# Uses regex to get volume from pactl
function get_volume {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

# Uses regex to get mute status from pactl
function get_mute {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'
}

# Returns a mute icon, a volume-low icon, or a volume-high icon, depending on the volume
function get_volume_icon {
    volume=$(get_volume)
    mute=$(get_mute)
    volume_icon=" "
    [ "$volume" -eq 0 ] || [ "$mute" == "yes" ] && volume_icon="🔇"
    [ "$volume" -lt 50 ] && volume_icon=" "
}

function get_album_art {
    # MPD support via mpc
    [ $enable_mpd_support = true ] && mpd=$(mpc current)
    url=$(playerctl -f "{{mpris:artUrl}}" metadata)
    album_art=""
    [[ $url == "file://"* ]] && album_art="${url/file:\/\//}"
    [[ $url == "http://"* ]] && [[ $download_album_art == "true" ]] && {
        # Identify filename from URL
        filename="$(echo $url | sed "s/.*\///")"
        # Download file to /tmp if it doesn't exist
        [ -f "/tmp/$filename" ] || wget -O "/tmp/$filename" "$url"
        album_art="/tmp/$filename"
    }
    [[ $url == "https://"* ]] && [[ $download_album_art == "true" ]] && {
        # Identify filename from URL
        filename="$(echo $url | sed "s/.*\///")"
        # Download file to /tmp if it doesn't exist
        [ -f "/tmp/$filename" ] || wget -O "/tmp/$filename" "$url"
        album_art="/tmp/$filename"
    }
    [ -n "$mpd" ] && {
        filename=$(mpc -f "%artist% - %album%" current)
        filepath=$(mpc -f "%file%" current)
        [ -f "/tmp/$filename" ] || ( mpc albumart "$filepath" > "/tmp/$filename" || mpc readpicture "$filepath" > "/tmp/$filename" )
        album_art="/tmp/$filename"
    }
}

# Displays a volume notification
function show_volume_notif {
    volume=$(get_mute)
    get_volume_icon
    [ $show_music_in_volume_indicator = false ] && notify-send -t $notification_timeout -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume "$volume_icon $volume%"
    [ $show_music_in_volume_indicator = true ] && {
        [ $enable_mpd_support = true ] && mpd=$(mpc current)
        # Get current title and artist
        current_song=$(playerctl -f "{{title}} - {{artist}}" metadata)
        [ -n "$mpd" ] && current_song="$mpd"
        # Get album art
        [ $show_album_art = true ] && get_album_art
        notify-send -t $notification_timeout -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume -i "$album_art" "$volume_icon $volume%" "$current_song"
    }
}

# Main function - Takes first argument e.g. "volume_up", "volume_down", "volume_mute"
case $1 in
    volume_up)
    # Unmutes and increases volume, then displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ 0
    volume=$(get_volume)
    [ $(( "$volume" + "$volume_step" )) -gt $max_volume ] && pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
    [ $(( "$volume" + "$volume_step" )) -gt $max_volume ] || pactl set-sink-volume @DEFAULT_SINK@ +$volume_step%
    show_volume_notif
    ;;
    volume_down)
    # Lowers volume and displays the notification
    pactl set-sink-volume @DEFAULT_SINK@ -$volume_step%
    show_volume_notif
    ;;
    volume_mute)
    # Toggles mute and displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    show_volume_notif
    ;;
esac
