#!/usr/bin/env bash

TODAY=$(date '+%-d')
HEAD=$(cal | head -n1)
BODY=$(cal -m | tail -n7 | sed -z "s|$TODAY|<u><b>$TODAY</b></u>|1")
dunstify -h string:x-canonical-private-synchronous:calendar "${HEAD}" "${BODY}" -u CRITICAL
