#!/usr/bin/env bash

# github https://github.com/Shringe/dunst-media-control

# See README.md for usage instructions
volume_step=2
max_volume=100
notification_timeout=1000 # in milliseconds
enable_mpd_support=true
download_album_art=true
show_album_art=true
show_music_in_volume_indicator=true

# Uses regex to get volume from pactl
function get_volume {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

# Uses regex to get mute status from pactl
function get_mute {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'
}

# Returns a mute icon, a volume-low icon, or a volume-high icon, depending on the volume
function get_volume_icon {
    volume=$(get_volume)
    mute=$(get_mute)
    if [ "$volume" -eq 0 ] || [ "$mute" == "yes" ] ; then
        volume_icon="🔇"
    elif [ "$volume" -lt 50 ]; then
        volume_icon=" "
    else
        volume_icon=" "
    fi 
}

function get_album_art {
    # MPD support via mpc
    [ $enable_mpd_support = true ] && mpd=$(mpc current)
    url=$(playerctl -f "{{mpris:artUrl}}" metadata)
    if [ -n "$mpd" ]; then
        filename=$(mpc -f "%artist% - %album%" current)
        filepath=$(mpc -f "%file%" current)
        [ -f "/tmp/$filename" ] || mpc readpicture "$filepath" > "/tmp/$filename"
        album_art="/tmp/$filename"
    elif [[ $url == "file://"* ]]; then
        album_art="${url/file:\/\//}"
    elif [[ $url == "http://"* ]] && [[ $download_album_art == "true" ]]; then
        # Identify filename from URL
        filename="$(echo $url | sed "s/.*\///")"

        # Download file to /tmp if it doesn't exist
        [ -f "/tmp/$filename" ] || wget -O "/tmp/$filename" "$url"

        album_art="/tmp/$filename"
    elif [[ $url == "https://"* ]] && [[ $download_album_art == "true" ]]; then
        # Identify filename from URL
        filename="$(echo $url | sed "s/.*\///")"
        
        # Download file to /tmp if it doesn't exist
        [ -f "/tmp/$filename" ] || wget -O "/tmp/$filename" "$url"

        album_art="/tmp/$filename"
    else
        album_art=""
    fi
}

# Displays a volume notification
function show_volume_notif {
    volume=$(get_mute)
    get_volume_icon

    if [[ $show_music_in_volume_indicator == "true" ]]; then
        [ $enable_mpd_support = true ] && mpd=$(mpc current)
        if [ -n "$mpd" ]; then
            current_song="$mpd"
        else
            current_song=$(playerctl -f "{{title}} - {{artist}}" metadata)
        fi

        if [[ $show_album_art == "true" ]]; then
            get_album_art
        fi
        notify-send -t $notification_timeout -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume -i "$album_art" "$volume_icon $volume%" "$current_song"
    else
        notify-send -t $notification_timeout -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume "$volume_icon $volume%"
    fi
}

# Main function - Takes user input, "volume_up", "volume_down", "brightness_up", or "brightness_down"
case $1 in
    # Volume =============================================================
    volume_up)
    # Unmutes and increases volume, then displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ 0
    volume=$(get_volume)
    if [ $(( "$volume" + "$volume_step" )) -gt $max_volume ]; then
        pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
    else
        pactl set-sink-volume @DEFAULT_SINK@ +$volume_step%
    fi
    show_volume_notif
    ;;

    volume_down)
    # Lowers volume and displays the notification
    pactl set-sink-volume @DEFAULT_SINK@ -$volume_step%
    show_volume_notif
    ;;

    volume_mute)
    # Toggles mute and displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    show_volume_notif
    ;;
esac
