#!/usr/bin/env bash

set -euo pipefail

# Funny colors
NoCol='\033[0m'
BPurple='\033[1;35m'
BGreen='\033[1;32m'
BYellow='\033[1;33m'
BRed='\033[1;31m'
BCyan='\033[1;36m'

echo 
echo -e "${BRed}! Checking suckless software !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dusk-sus${NoCol}"
diff --color ~/dusk-sus/config.h ~/Dotfiles/dusk-sus/config.h
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dmenu-sus${NoCol}"
diff --color ~/dmenu-sus/config.h ~/Dotfiles/dmenu-sus/config.h
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}st-sus${NoCol}"
diff --color ~/st-sus/config.h ~/Dotfiles/st-sus/config.h
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}slstatus-sus${NoCol}"
diff --color ~/slstatus-sus/config.h ~/Dotfiles/slstatus-sus/config.h
echo 

echo -e "${BRed}! Checking PATH scripts !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}hub-script${NoCol}"
diff --color /usr/local/bin/hub-script ~/Dotfiles/.local/bin/hub-script
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}conky-toggle${NoCol}"
diff --color /usr/local/bin/conky-toggle ~/Dotfiles/.local/bin/conky-toggle
echo
echo -e "${BGreen}! Everything is synced !${NoCol}"
echo 
