#!/usr/bin/env bash

set -euo pipefail

# Funny colors
NoCol='\033[0m'
BPurple='\033[1;35m'
BGreen='\033[1;32m'
BYellow='\033[1;33m'
BRed='\033[1;31m'
BCyan='\033[1;36m'

echo 
echo -e " ${BRed}! Checking suckless software !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dusk-sus${NoCol}"
diff -r -q ~/dusk-sus ~/Dotfiles/dusk-sus | grep -v "^Only in" || :
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dmenu-sus${NoCol}"
diff -r -q ~/dmenu-sus ~/Dotfiles/dmenu-sus | grep -v "^Only in" || :
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}st-sus${NoCol}"
diff -r -q ~/st-sus ~/Dotfiles/st-sus | grep -v "^Only in" || :
echo 

echo -e " ${BRed}! Checking PATH scripts !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}hub-script${NoCol}"
diff --color /usr/local/bin/hub-script ~/Dotfiles/.local/bin/hub-script
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}conky-toggle${NoCol}"
diff --color /usr/local/bin/conky-toggle ~/Dotfiles/.local/bin/conky-toggle
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}update-status.sh${NoCol}"
diff --color /usr/local/bin/update-status.sh ~/Dotfiles/.local/bin/update-status.sh
echo
echo -e " ${BGreen}! Diff check DONE !${NoCol}"
echo 
