#!/usr/bin/env bash

set -euo pipefail

# Funny colors
NoCol='\033[0m'
BPurple='\033[1;35m'
BGreen='\033[1;32m'
BYellow='\033[1;33m'
BRed='\033[1;31m'
BCyan='\033[1;36m'

echo 
echo -e " ${BRed}! Checking suckless software !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dusk-sus${NoCol}"
diff -r -q ~/dusk-sus ~/Dotfiles/dusk-sus | grep -v "^Only in" || :
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}dmenu-sus${NoCol}"
diff -r -q ~/dmenu-sus ~/Dotfiles/dmenu-sus | grep -v "^Only in" || :
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}st-sus${NoCol}"
diff -r -q ~/st-sus ~/Dotfiles/st-sus | grep -v "^Only in" || :
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}slstatus-sus${NoCol}"
diff -r -q ~/slstatus-sus ~/Dotfiles/slstatus-sus | grep -v "^Only in" || :
echo 

echo -e " ${BRed}! Checking PATH scripts !${NoCol}"
echo 
echo -e "${BPurple}>> ${BCyan}diff${NoCol} of ${BYellow}root-menu${NoCol}"
diff --color /usr/local/bin/root-menu ~/Dotfiles/.local/bin/root-menu
echo
echo -e " ${BGreen}! Diff check DONE !${NoCol}"
echo 
