#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --vsync -b &

polybar-toggle

xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5

bspc config normal_border_color  "#282C34"
bspc config focused_border_color "#51AFEF"

bspc config border_width           1
bspc config window_gap             12

bspc config split_ratio            0.50
bspc config focus_follows_pointer  true

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config single_monocle         true
