/* Patches */
#include "alpha.h"
#include "boxdraw.h"
#include "font2.h"
#include "keyboardselect_reflow_st.h"
#include "keyboardselect_reflow_x.h"
#include "netwmicon_icon.h"
#include "netwmicon.h"
#include "xresources.h"
#include "osc133.h"
