/* Patches */
#include "alpha.c"
#include "boxdraw.c"
#include "fixkeyboardinput.c"
#include "font2.c"
#include "keyboardselect_reflow_x.c"
#include "netwmicon_legacy.c"
#include "openurlonclick.c"
#include "xresources.c"
#include "osc133.c"
