[mgr]
linemode = "size"
sort_by = "alphabetical"
sort_dir_first = true
show_hidden = true
[opener]
edit = [
	{ run = 'helix "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
	{ run = 'helix "$@"', block = true, desc = "helix" },
	{ run = 'mpv "$@"', orphan = true, desc = "mpv" },
	{ run = 'nsxiv -a -b "$@"', orphan = true, desc = "nsxiv" },
]
[preview]
image_quality = 75
sixel_fraction = 10
max_width = 960
max_height = 1600
