
format = """
[ $time\
$username\
$cmd_duration\
$directory\
$git_branch\
$git_commit\
$git_status\
\n $character\
$status](bold white)"""

# cool characters:    ,    ,   ,    ,  

[character]
success_symbol = '[  ](bold white)'
error_symbol = '[  ](bold red)'

[username]
format = "[ [$user ](bold white bg:black)](bold black)"
show_always = true
disabled = false

[directory]
format = "[󰫢  [$path](bold white bg:black)[](bold black)](bold white bg:black)"
home_symbol = "󱂵 "

[hostname]
ssh_only = false
format = '[$hostname](bold purple)'

[time]
format = "[[󰪠 $time](bold black bg:white) 󰁥](bold white)"
disabled = false

[cmd_duration]
format = "[took [$duration ](bold red bg:black)](bold white bg:black)"

[status]
format = '[$symbol $status ](bold red)'
disabled = false

[git_branch]
format = "[[   ](bold purple) [$symbol$branch ](bold black bg:purple)](bold black bg:purple)"

[git_commit]
only_detached = false
format = '[\($hash$tag\) ](bold black bg:purple)'

[git_status]
format = '[[\[$all_status$ahead_behind\] ](bold black bg:purple) ](bold purple)'
# modified = '[\($count\)!](bold black bg:purple)'
# staged = '[++\($count\)](bold black bg:purple)'
