#!/usr/bin/env bash
# Dependencies: wireplumber, jq, pipewire-pulse, mpv

set -eo pipefail

. $HOME/Scripts/script-vars

[ ! -d "$soundsdir" ] && notify-send -i error "Ambience Tool" "Sounds directory doesn't exist" && exit 1
pidfile="/tmp/ambientpid"

startsound()
{
  [ -z "$1" ] && exit 1
  [ "$1" = "select" ] && file=$(find "${soundsdir}" \( -iname "*.mp3" -o -iname "*.m4a" -o -iname "*.ogg" \) -printf '%P\n' | sort | $menu "Select:" -1 -R -n)
  [ "$1" = "random" ] && file=$(find "${soundsdir}" \( -iname "*.mp3" -o -iname "*.m4a" -o -iname "*.ogg" \) -printf '%P\n' | shuf -n 1)
  kill "$(cat $pidfile)" || :
  mpv --no-video --force-window=no --loop "${soundsdir}/${file}" >/dev/null 2>&1 &
  pid=$!
  echo "$pid" > "$pidfile"
  notify-send -i info "Ambience Tool" "Now playing: $file :3"
}

volume()
{
  [ ! -f "$pidfile" ] && notify-send -i info "Ambience Tool" "No active mpv found!" && exit 1
  pid=$(cat "$pidfile")
  pwid=$(pactl -f json list sink-inputs | jq -r '.[] | .properties."application.process.id" + " " + .properties."object.id"' | grep "$pid" | awk '{print $2}')
  volume=$(wpctl get-volume "$pwid" | awk '{print $2}')
  setvolume=$(printf "$volume" | $menu "Volume for ambience:")
  wpctl set-volume "$pwid" $setvolume
  notify-send -i info "Pipewire Tool" "Set volume: $setvolume for ambience :3"
}

stopsound()
{
  kill "$(cat $pidfile)" && notify-send -i info "Ambience Tool" "Stopped active sound :3" || notify-send -i error "Ambience Tool" "No sound is playing right now :("
  rm "$pidfile"
}

[ -z "$mainchoice" ] && mainchoice=$(printf ":g  Select sound\n:p  Random sound\n:y  Volume\n:r  Stop" | $menu "Choose:" -R -n -1 | $cutemoji)
[ "$mainchoice" = "Select sound" ] && startsound select
[ "$mainchoice" = "Random sound" ] && startsound random
[ "$mainchoice" = "Volume" ] && volume
[ "$mainchoice" = "Stop" ] && stopsound

exit 0
