#!/usr/bin/env bash
# Dependencies: Color picker that outputs hex to stdout

set -eo pipefail

. $HOME/Scripts/script-vars

histfile="$HOME/.cache/colorcache"

# Refactored version of https://github.com/NoTArZuZ/Dotfiles-NixOS
# Functions
pickcolor() {
  hex=$($colpick)
  echo "$hex" >>  "$histfile"
  echo "$hex" | $cp2cb
  notify-send -i info "Color Picker Tool" "The picked color is: $hex (Copied to clipboard)"
  exit 0
}

clearcache() {
  [ ! -e "$histfile" ] && notify-send -i error "Color Picker Tool" "Color cache is empty, nothing is removed" && exit 1
  rm "$histfile"
  notify-send -i info "Color Picker Tool" "Cleared color cache"
  exit 0
}

[ "$1" = "pick" ] || [ "$1" = "-p" ] && mainmethod="Pick"
[ "$1" = "clear" ] || [ "$1" = "-c" ] && mainmethod="Clear"

[ ! -e "$hisfile" ] && touch "$histfile"
history=$(cat "$histfile")

# Dmenu Choice
[ "$mainmethod" ] || mainmethod=$(printf "Pick\nClear\n$history" | $menu "Choose:" -1 -R -n)

# Main Program
[ "$mainmethod" = "Pick" ] && pickcolor
[ "$mainmethod" = "Clear" ] && clearcache
[ "$mainmethod" = "$(grep -x -F "$mainmethod" $histfile)" ] && echo "$mainmethod" | xclip -r -selection clipboard &&
  notify-send -i info "Color Picker Tool" "Copied color: $mainmethod" && exit 0

exit 1
