#!/usr/bin/env bash
# Dependencies: Color picker that outputs hex to stdout

set -eo pipefail

. $HOME/Scripts/script-vars

# Refactored version of https://github.com/NoTArZuZ/Dotfiles-NixOS
# Functions
pickcolor() {
  hex=$($colpick)
  echo "$hex" >>  $HOME/.cache/colorcache
  echo "$hex" | $cp2cb
  notify-send -i info "Color Picker Tool" "The picked color is: $hex (Copied to clipboard)"
  exit 0
}

listcache() {
  [ ! -e $HOME/.cache/colorcache ] && notify-send -i error "Color Picker Tool" "Color cache is empty" && exit 1
  selecthex=$(cat $HOME/.cache/colorcache | $menu "Select color:" -R -l $(cat $HOME/.cache/colorcache | wc -l))
  echo "$selecthex" | $cp2cb
  notify-send -i info "Color Picker Tool" "The $selecthex color is copied to clipboard"
  exit 0
}

clearcache() {
  [ ! -e $HOME/.cache/colorcache ] && notify-send -i error "Color Picker Tool" "Color cache is empty, nothing is removed" && exit 1
  rm $HOME/.cache/colorcache
  notify-send -i info "Color Picker Tool" "Cleared color cache"
  exit 0
}

# Arguments
[ $1 ] && {
  [ "$1" = "pick" ] || [ "$1" = "-p" ] && mainmethod="Pick"
  [ "$1" = "list" ] || [ "$1" = "-l" ] && mainmethod="List"
  [ "$1" = "clear" ] || [ "$1" = "-c" ] && mainmethod="Clear"
  [ "$mainmethod" ] || exit 1
}

# Dmenu Choice
[ "$mainmethod" ] || mainmethod=$(printf ":g  Pick\n:y  List\n:r  Clear" | $menu "Choose:" -l 3 -1 -R -n | $cutemoji)

# Main Program
[ "$mainmethod" = "Pick" ] && pickcolor
[ "$mainmethod" = "List" ] && listcache
[ "$mainmethod" = "Clear" ] && clearcache

exit 1
