#!/usr/bin/env bash
# Dependencies: localsend ezscrcpy

set -eo pipefail

. ~/Scripts/script-vars

setup_mirror()
{
  paired=$(printf "y\nn" | $menu "Have you paired with PC?" -1 -R -n)
  [ "$paired" = "n" ] && notify-send -i error "Phone Manager" "Please pair your PC with the phone via adb" && exit 1
  ip=$(echo "" | $menu "Enter IP:")
  port_connect=$(echo "" | $menu "Enter Port:")
}

mirror()
{
  [ "$1" = webcam ] && {
    facing=$(printf "front\nback" | $menu "Camera Facing:" -1 -R -n)
    [ "$facing" = "front" ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -w
    [ "$facing" = "back" ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -b -w
  }
  [ "$1" = screen ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -s
  [ "$1" = audio ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -a
}

mainchoice=$(printf ":y  Fileshare\n:p  Screen Mirror\n:g  Webcam\n:r  Cast Audio" | $menu "Choose:" -1 -R -n | $cutemoji)
[ "$mainchoice" = "Fileshare" ] && localsend
[ "$mainchoice" = "Screen Mirror" ] && { setup_mirror; mirror screen; }
[ "$mainchoice" = "Webcam" ] && { setup_mirror; mirror webcam; }
[ "$mainchoice" = "Cast Audio" ] && { setup_mirror; mirror audio; }
