#!/usr/bin/env bash
# Dependencies: localsend ezscrcpy

set -eo pipefail

. ~/Scripts/script-vars

setup_mirror()
{
  ip=$(echo "" | $menu "Enter Device IP:")
  port_connect=$(echo "" | $menu "Enter Connection Port:")
  paired=$(printf "Yes\nNo" | $menu "Have you paired with PC?" -1 -R -n)
  [ "$paired" = "No" ] && {
    port_pair=$(echo "" | $menu "Enter Pair Port:")
    code=$(echo "" | $menu "Enter Pair Code:")
    adb pair $ip:$port_pair $code || { notify-send -i error "Phone Manager" "Failed to pair the device"; exit 1; }
    notify-send -i info "Phone Manager" "The device was successfully paired"
  }
  return 0
}

mirror()
{
  [ "$1" = webcam ] && {
    facing=$(printf "front\nback" | $menu "Camera Facing:" -1 -R -n)
    [ "$facing" = "front" ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -w
    [ "$facing" = "back" ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -b -w
  }
  [ "$1" = screen ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -s
  [ "$1" = audio ] && ip="$ip" port_connect="$port_connect" ezscrcpy -r -a
  exit 0
}

mainchoice=$(printf ":y  Fileshare\n:p  Screen Mirror\n:g  Webcam\n:r  Cast Audio" | $menu "Choose:" -1 -R -n | $cutemoji)
[ "$mainchoice" = "Fileshare" ] && localsend
[ "$mainchoice" = "Screen Mirror" ] && { setup_mirror; mirror screen; }
[ "$mainchoice" = "Webcam" ] && { setup_mirror; mirror webcam; }
[ "$mainchoice" = "Cast Audio" ] && { setup_mirror; mirror audio; }
