#!/usr/bin/env bash

set -eo pipefail

. $HOME/Scripts/script-vars

mainchoice=$(ps --user "$USER" -F | awk '{print $2" "$11}' | tail -n +2 | $menu "Select:" -R -1)
[[ -n "$mainchoice" ]] && {
  confirm=$(printf "Yes\nNo" | $menu "Kill $mainchoice?" -R -1 -n)
  [ "$confirm" == "Yes" ] && kill -9 "${mainchoice%% *}"
}

exit 0
