#!/usr/bin/env bash
# Dependencies: libqalculate

set -eo pipefail

. $HOME/Scripts/script-vars

history_file="$HOME/.cache/calculatorcache"

is_in_history() { grep -q -x -F "$1" $history_file; }

add_to_history() { echo "$1" >> $history_file; }

copy_to_clipboard() { printf "$1" | xclip -sel clip; }

result_from_equation() { printf "$1" | sed 's/^.*\(=\|≈\) //'; }

main() {
    while
        [[ ! -f $history_file ]] && mkdir -p $(dirname $history_file) && touch $history_file
        [[ ! -s $history_file ]] && hist="No history found" || hist=$(tac $history_file)
        input=$(printf "$hist\nClear" | ${menu} "Calculator:" "$@")
        [[ -n $input ]] # quit == no input
    do
        [ "$input" = "Clear" ] && rm "$history_file" || {
            equation=$( is_in_history "$input" && echo "$input" || echo "$(qalc $input)" )
            is_in_history "$equation" || add_to_history "$equation"
            copy_to_clipboard $(result_from_equation "$equation")
        }
    done
}

main "$@"
