#!/usr/bin/env bash
# Dependencies: j4-dmenu-desktop

set -euo pipefail

. $HOME/Scripts/script-vars

# Refactored version of https://github.com/NoTArZuZ/Dotfiles-NixOS
# Tried to make this one myself but too dumb for more advanced parsing
j4-dmenu-desktop --dmenu="$menu 'Launch:' -l 10 -1 -R"
