#!/usr/bin/env bash
# Dependencies: Image viewer that outputs marked image path to stdout, xwinwrap (optional for gif and mp4)

set -eo pipefail

. $HOME/Scripts/script-vars

# Refactored version of https://github.com/NoTArZuZ/Dotfiles-NixOS
# Functions
setwallpaper() {
  case $bgfile in
  *.mp4|*.gif)
    scrres=$(xrandr | grep "current" | awk '{print $8 $9 $10}' | sed 's/.\{1\}$//')
    pkill -x xwinwrap || :
    echo "$bgfile" > "$HOME/.cache/wallcache"
    xwinwrap -g ${scrres}+0+0 -un -fdt -ni -b -nf -ov -- mpv-wallpaper WID $bgfile &
  ;;
  *)
    pkill -x xwinwrap || :
    echo "$bgfile" > "$HOME/.cache/wallcache"
    $setbg $bgfile
  ;;
  esac
}

selectbg() {
  bgfile=$($imgview "$wallpaperdir" | shuf -n 1)
  setwallpaper
  notify-send --icon=info "Wallpaper Tool" "Changed wallpaper to $bgfile"
  exit 0
}

randombg() {
  rollmore="No"
  until [ "$rollmore" = "Yes" ]; do
    bgfile=$(find "$wallpaperdir" -type f | shuf -n 1)
    setwallpaper
    notify-send --icon=info "Wallpaper Tool" "Changed wallpaper to $bgfile"
    rollmore=$(printf ":r  No\n:g  Yes" | $menu "Do you like it?" -1 -R -n | $cutemoji)
  done
  exit 0
}

# Arguments
[ $1 ] && {
  [ "$1" = "set" ] || [ "$1" = "-s" ] && mainmethod="Select"
  [ "$1" = "random" ] || [ "$1" = "-r" ] && mainmethod="Random"
  [ "$1" = "manual" ] || [ "$1" = "-m" ] && mainmethod="Manual"
  [ "$1" = "restore" ] || [ "$1" = "-l" ] && mainmethod="Restore"
  [ "$mainmethod" ] || exit 1
}

# Dmenu Choice
[ "$mainmethod" ] || mainmethod=$(printf ":g  Select\n:p  Random" | $menu "New Wallpaper:" -1 -R -n | $cutemoji)

# Main Program
[ "$mainmethod" = "Select" ] && selectbg
[ "$mainmethod" = "Random" ] && randombg
[ "$mainmethod" = "Manual" ] && { bgfile="$2"; setwallpaper; exit 0; }
[ "$mainmethod" = "Restore" ] && { bgfile=$(cat $HOME/.cache/wallcache); setwallpaper; exit 0; }

exit 1
