#!/usr/bin/env bash
# Dependencies: Image viewer that outputs marked image path to stdout

set -eo pipefail

. $HOME/Scripts/script-vars

# Refactored version of https://github.com/NoTArZuZ/Dotfiles-NixOS
# Functions
setwallpaper() {
  ln -sf "$bgfile" $HOME/.cache/wallcache
  $setbg $HOME/.cache/wallcache
  notify-send --icon=info "Wallpaper Tool" "Changed wallpaper to $bgfile"
}

selectbg() {
  bgfile=$($imgview "$wallpaperdir" | shuf -n 1)
  setwallpaper
  exit 0
}

randombg() {
  rollmore="No"
  until [ "$rollmore" = "Yes" ]; do
    bgfile=$(find "$wallpaperdir" -type f | shuf -n 1)
    setwallpaper
    rollmore=$(printf ":r  No\n:g  Yes" | $menu "Do you like it?" -l 2 -1 -R -n | $cutemoji)
  done
  exit 0
}

# Arguments
[ $1 ] && {
  [ "$1" = "set" ] || [ "$1" = "-s" ] && mainmethod="Select"
  [ "$1" = "random" ] || [ "$1" = "-r" ] && mainmethod="Random"
  [ "$mainmethod" ] || exit 1
}

# Dmenu Choice
[ "$mainmethod" ] || mainmethod=$(printf ":g  Select\n:p  Random" | $menu "New Wallpaper:" -l 2 -1 -R -n | $cutemoji)

# Main Program
[ "$mainmethod" = "Select" ] && selectbg
[ "$mainmethod" = "Random" ] && randombg

exit 1
