#!/usr/bin/env bash

set -eo pipefail

. $HOME/Scripts/script-vars

[ -z "$mainchoice" ] && mainchoice=$(printf ":b  Sync\n:r  Remove\n:p  Update" | $menu "Choose:" -R -1 -n | $cutemoji)

[ "$mainchoice" = "Sync" ] && {
  package=$(yay -Slq | $menu "Sync:" -l 15 -g 3 -R | tr '\n' ' ')
  st -c Nsxiv -g 125x38 -e yay -S $package
}

[ "$mainchoice" = "Remove" ] && {
  package=$(yay -Qq | $menu "Remove:" -l 15 -g 3 -R | tr '\n' ' ')
  st -c Nsxiv -g 125x38 -e yay -Runs $package
}

[ "$mainchoice" = "Update" ] && {
  package=$(yay -Qu | wc -l)
  confirm=$(printf "Yes\nNo" | $menu "Update? ($package)" -R -1 -n)
  [ "$confirm" = "Yes" ] && st -c Nsxiv -g 125x38 -e "$SHELL" -c 'yay; read line'
}

exit 0
