music_directory    "http://192.168.0.102:3923/music/"
playlist_directory "~/.config/mpd/playlists"
db_file			   "~/.config/mpd/database"
log_file		   "~/.config/mpd/log"
pid_file		   "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file	   "~/.config/mpd/sticker.sql"
bind_to_address	   "0.0.0.0"
port			   "6600"
log_level		   "notice"
restore_paused     "no"
save_absolute_paths_in_playlists "no"
auto_update	       "yes"
replaygain		   "off"
metadata_to_use    "+comment"

input {
	plugin "curl"
}

input {
	plugin "cdio_paranoia"
}

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

#audio_output {
#        type            "pulse"
#        name            "discord"
#}

audio_output {
    type                   "fifo"
    name                   "Visualizer"
    format                 "44100:16:2"
    path                   "/tmp/mpd.fifo"
}
