[Connection]
host = 127.0.0.1
port = 6600

[Library]
music_dir = http://192.168.0.102:3923/music/
cover_regex = ^(album|cover|\.?folder|front).*\.(gif|jpeg|jpg|png)$

[Bling]
notify = False
notify_paused = True
mmkeys = True
cdprev = True

[Notify]
urgency = 0
timeout = -1
summary =
body =
paused_summary =
paused_body =
